	cmake_minimum_required(VERSION 2.6)
	add_executable(	essai /essai.cpp	)
	add_executable(	main /main.cpp	)
	add_executable(	activite activite/activite.cpp	)
	add_executable(	detente detente/detente.cpp	)
	add_executable(	escalade escalade/escalade.cpp	)
	add_executable(	etape etape/etape.cpp	)
	add_executable(	lieu lieu/lieu.cpp	)
	add_executable(	monument monument/monument.cpp	)
	add_executable(	naturel naturel/naturel.cpp	)
	add_executable(	rando rando/rando.cpp	)
	add_executable(	sport sport/sport.cpp	)
	add_executable(	urbain urbain/urbain.cpp	)